# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b7b5d0f87fcf0e56231aeb1aaeb3086f44ff2c82a2b3dd930d613f7ccd26e3c2ba41185b04b9137db757248209b6d40240311824defadc22fcb781d6428896

test:
  secret_key_base: 84ea37a7699e473392ba070b91cf676d31aca4d0547e63fe0cdea5d1d968a2cfd54f5e52477d5dd92a9bd94d6721fea2b0e0456350054c9b280352bd8414b1d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
